version: '2'
networks:
  front-tier:
    external:
      name: nginx-Default
  back-tier:
    driver: bridge
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    env_file:
      - ./env
    networks:
    - back-tier
  app:
    image: known
    restart: always
    links:
      - db
    volumes:
      - ./data:/var/www/html/Uploads
    env_file:
      - ./env
    networks:
    - back-tier
  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      VIRTUAL_HOST: 'y.te.gs'
      LETSENCRYPT_HOST: 'y.te.gs'
      LETSENCRYPT_EMAIL: 'support@ecobytes.net' 
    networks:
    - front-tier
    - back-tier
