known-allmende-db:
  image: mysql
  volumes:
    - ./mysql/runtime:/var/lib/mysql
  env_file:
    - ./.env
  restart: always
known-allmende-app:
  image: allmende/known
  links:
    - known-allmende-db:db
  volumes:
    - ./data:/var/www/html/Uploads
  env_file:
    - ./.env
  restart: always
known-allmende-web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - known-allmende-app:app
  volumes_from:
    - known-allmende-app
  expose:
    - "80"
  environment:
    VIRTUAL_HOST: 'f.q.dn'
    VIRTUAL_PORT: '80'
  restart: always
